name: Publish Docker image

on:
  push:
    # branches: [ "main" ]
    tags:
      - "v*.*.*"
  # release:
  #   types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker tag
        id: extract_tag
        run: echo "DOCKER_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_EN

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            suapapa/ko-epggrab:latest
            suapapa/ko-epggrab:${{ env.DOCKER_TAG }}
